export interface User {
    _id?:string,
    email: string,
    password:string,
    userType: string,
    dateCreated: string,
    firstName: string,
    lastName: string,
    profession: string,
    companyName: string,
    industry: string,
    imagePath: string,
    country: string,
    summary: string,
    skills: string[],
    experience: any[],
    education: any[],
    packages: any[],
    billingAddress: string,
    rating: string[],
    bookmarks: string[],
    status: string,
    confirmationCode: string,
    logIns:string[],
}
